# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
        ('ingreso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='producto',
            field=models.ManyToManyField(to='producto.Producto'),
        ),
    ]
